---
version: "3.2"
services:
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      - frontend
      - backend
  php:
    build: './php/'
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID}
      GOOGLE_ANALYTICS_ID: ${GOOGLE_ANALYTICS_ID}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TWILIO_SID: ${TWILIO_SID}
      TWILIO_AUTH: ${TWILIO_AUTH}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      DAILY_SEND_BATCH_SIZE: ${DAILY_SEND_BATCH_SIZE}
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      - backend
  mysql:
    build: './mysql/'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend
networks:
  frontend:
  backend:
